### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by wkrueger** [wkrueger/blog-draft#1]
- [ ] Add date and author to main post template
 - [ ] Fix form pages display (add container)
 - [ ] Create admin page for global blog options

**Longer term**
 - [ ] Tags
 - [ ] Custom hbs templates
 - [ ] Personalize .hbs data injecting (for templates)
 - [ ] Custom routes > custom templates

**Comment by wkrueger** [comment]
test
 - [ ] Add date and author to main post template
 - [ ] Fix form pages display (add container)
 - [ ] Create admin page for global blog options
 - [ ] Tags
 - [ ] Custom hbs templates
 - [ ] Personalize .hbs data injecting (for templates)
 - [ ] Custom routes > custom templates
