### ISSUE TITLE
Theme spec draft.

### ISSUE THREAD

**Issue by wkrueger** [wkrueger/blog-draft#5]
Theme coding becoming cumbersome. Writing a draft for guidance.

## Task list

 - [x] Manually get params when using custom routes
 - [x] Implement tags
 - [x] Check slink + ?id=XX
 - [x] Implement template helpers
 - [x] Remove default article list route. Replace with minimal start-up custom routes
 - [x] Implement feeds and rendering actions
   - [x] ( list feed ok )
   - [x] ( slink feed ok )
   - [x] ( write down the whole thing )
 - [x] `scripts` and `stylesheets`
 - [x] Implement custom fields (ex: The index of a post for a landing page)

## Theme

* A `theme` contains a collection of `models`. Each model specifies:
    * An identifier `key` and a `name`  
    * A rendering function.`list` for a list, `slink` for a single article
        * `list` may take the `skip`, `count` and `raw` params
        * `slink` mak take the `slink` and `id` params
    * A template file (currently handlebars). The template may have access for some helpers:
        * `{{ link ["route" routename] ["model" modelname] ["theme" themename] ["skip" skipval] ["count" countval] ["raw" rawval] ["slink" slinkval] ["id" idval] }}`
        * An existing route MUST be matched in order for a link to be generated. A resolution routine tries to match one route based on the params. (a theme maker may specify just "model", for instance).
        * If a route is not directly pointed (by identifier), a route with the specified model and marked as MAIN is matched (the first one, actually).
        * If a route has placeholders, the values are merged inside them. Otherwise they are appended as query parameters.
        * **`{{ themeresource path }}`**.  ex: `{{ resource img/bg2.png }}`, simply points to the theme's public static file mount.
    * A list of `feeds`. Each feed populates an object in the template scope with an array. A feed may define
        * Its mounting point (`key`)
        * A rendering `action`
    * Custom params? Custom fields? Later. 2.0.

Sum it up

```typescript
declare interface Theme {
    _reference; //taken from its mounting folder
    _splashImg; //convenience link
    name;
    description;
    models : ThemeModel[]
}


declare interface ThemeModel {
    key: string
    name: string
    template: string
    type: ThemeModelType; // declared as string, converted to int on load
    feeds: { key: string; action?: RenderingAction }[]
}

declare enum ThemeModelType {
    list, slink
}
```

## Route
* ~~The default routes try to follow a "RESTful" principle. Which may make them clumsy for presentation.~~ The default view routes are gone.
* Associate a defined theme model to a route. Also add a name identifier.
* May define params inside the route. Ex: `/about-us/personnel/:id`
* May define fixed params. Which will override everything else passed.
* The params are the same as the ones from the `model-route` helper above. skip, count, raw, slink, id.
* Custom params? Later maybe? Let's see what we will need.
* Remove the default display routes. Make them custom routes.

Sum it up.

```typescript
declare interface Route {
    id?: number
    route: string
    theme: string
    model: string
    param?: {
        id
        slink
        skip
        count
        raw
    }
    _test? : RegExp //generated when mounted
}
```

## Rendering action

 - Initially provide a basic parameter-based configuration (no code).
 
```typescript
declare interface RenderingAction {
    selectTags? : string[]
    selectFields? : string[] //(here it comes custom fields)
    limit?: number
}
```

Themes and routes are changed on-the-fly, without the need of a server restart.

Themes and routes metadata are kept in-memory, refreshed on server start or any change request.

Post id vs slink cached in memory (with a size limit) for faster link generation.
